PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGSP26_WF_CONF CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGSP26_WF_CONF-WF_TYPE .
    FIELD ZGSP26_WF_CONF-SRV_PATH .
    FIELD ZGSP26_WF_CONF-ENTITY_SET .
    FIELD ZGSP26_WF_CONF-SUB_ENT_SET .
    FIELD ZGSP26_WF_CONF-EXPAND_NAV .
    FIELD ZGSP26_WF_CONF-EXPAND_NAV2 .
    FIELD ZGSP26_WF_CONF-SEM_OBJ .
    FIELD ZGSP26_WF_CONF-SEM_ACT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGSP26_WF_CONF-WF_TYPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
